---
- name: Remove ppa repo.
  ansible.builtin.apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: Remove older signing key
  ansible.builtin.apt_key:
    id: "7fa2af80"
    state: absent

- name: Add keyring
  ansible.builtin.apt:
    deb: "https://developer.download.nvidia.com/compute/cuda/repos/{{ ansible_distribution | lower }}{{ ansible_distribution_version | replace('.', '') }}/{{ ansible_architecture }}/cuda-keyring_1.0-1_all.deb"
    state: "present"

- name: Install kmod
  ansible.builtin.apt_key:
    name: kmod
    state: present
    update_cache: true

- name: Install nvidia drivers.
  ansible.builtin.apt:
    name: "cuda-drivers-{{ driver_version }}"
    state: present
    autoremove: true
    update_cache: true
